### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by Reinhold-1591** [pyzo/pyzo#1050]
I'am real in trouble! I would like to run some Python Files which uses Tensorflow but it does not work as I expectet. I get the following 
error messages. I would be good if you can help me out with this issue.

```
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) on Windows (64 bits).
This is the Pyzo interpreter with integrated event loop for ASYNCIO.
Type 'help' for help, type '?' for a list of *magic* commands.

>>> import numpy

>>> import tensorflow
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Reinhold Kwauka\AppData\Roaming\Python\Python311\site-packages\tensorflow\__init__.py", line 42, in <module>
    from tensorflow.python import tf2 as _tf2
  File "C:\Users\Reinhold Kwauka\AppData\Roaming\Python\Python311\site-packages\tensorflow\python\tf2.py", line 21, in <module>
    from tensorflow.python.platform import _pywrap_tf2
ImportError: DLL load failed while importing _pywrap_tf2: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.
```

WIth best gegards,
reinhold Kwauka

**Comment by almarklein** [comment]
It looks like Tensorflow is not installed properly. See e.g. this page https://www.tensorflow.org/install
