### ISSUE TITLE
Workspace does not display numpy quaternions

### ISSUE THREAD

**Issue by wolfgangr** [pyzo/pyzo#1051]
reproduce along this instructions:
https://quaternion.readthedocs.io/en/latest/

```
pip install --upgrade --force-reinstall numpy-quaternion
import numpy as np
import quaternion
one = np.quaternion(1,0,0,0)
a =6
q1 = np.quaternion(1,2,3,4)
q2 = np.quaternion(5,6,7,8)
a = np.array([q1, q2])
whos
```

Most things work as expected.
However, variables `one`, `q1`, `q2`, i.e. plain numpy quaternions, are not shown in `pyzo`'s Workspace view.
They are listed, though, in `whos` output as
```
one                 quaternion          quaternion(1, 0, 0, 0)                  
q1                  quaternion          quaternion(1, 2, 3, 4)                  
q2                  quaternion          quaternion(5, 6, 7, 8)  
```
Expected behaviour:
These variables should be listed (and introspectable) in the `pyzo` Worspace view as well.

The array a consisting of two quaternions is visible in the workspace.
```
>>> a
array([quaternion(1, 2, 3, 4), quaternion(5, 6, 7, 8)], dtype=quaternion)
```

```
Pyzo version: 4.15.0 (source)
Platform: linux
Python version: 3.7.3
Qt version: 5.11.3
PyQt5 version: 5.11.3
```

**Comment by wolfgangr** [comment]
thanks for the quick response.

tried to install it from git
However, looks like I've screwed up something else...

```
wrosner@wjrws3:~/.local/bin$ /home/wrosner/test/pyzo/pyzo/pyzolauncher.py
Traceback (most recent call last):
  File "/home/wrosner/test/pyzo/pyzo/pyzolauncher.py", line 54, in <module>
    pyzo.start()
  File "/home/wrosner/test/pyzo/pyzo/pyzo/__init__.py", line 54, in start
    from ._start import start
  File "/home/wrosner/test/pyzo/pyzo/pyzo/_start.py", line 16, in <module>
    from pyzo.util import paths
  File "/home/wrosner/test/pyzo/pyzo/pyzo/util/paths.py", line 7, in <module>
    from pyzo.qt import QtCore
  File "/home/wrosner/test/pyzo/pyzo/pyzo/qt/__init__.py", line 65, in <module>
    from . import qtutils
  File "/home/wrosner/test/pyzo/pyzo/pyzo/qt/qtutils.py", line 19, in <module>
    import PyQt5.sip as _sip
ModuleNotFoundError: No module named 'PyQt5.sip'
```

**Comment by wolfgangr** [comment]
I have raised an extra issue for the 'PyQt5.sip' message
https://github.com/pyzo/pyzo/issues/1053

To proceed with my quaternions, I applied your commit manually to 4.15

Looks like it works :-)

```
~/test/pyzo/pyzo_dev_4_15/pyzo-main/pyzo/pyzokernel$ diff introspection.py_000 introspection.py
302,305c302,307
<                         tmp = str(float(val))
<                         if "int" in val.dtype.name:
<                             tmp = str(int(val))
<                         repres = "<array scalar %s (%s)>" % (val.dtype.name, tmp)
---
>                         # tmp = str(float(val))
>                         # if "int" in val.dtype.name:
>                         #     tmp = str(int(val))
>                         # repres = "<array scalar %s (%s)>" % (val.dtype.name, tmp)
> # https://github.com/pyzo/pyzo/commit/ac9370fa9c6f7a0c78d17975bbd3d67e77f9e534
>                         repres = "<array scalar %s (%s)>" % (val.dtype.name, str(val))
```
