### ISSUE TITLE
Minor bug : Crash when inserting Emoji

### ISSUE THREAD

**Issue by matthias4217** [pyzo/pyzo#473]
I tried to write 😅 in Pyzo, because I wanted to test the ability of Python to handle Emojis. However, after a second when the "😅" was visible on Pyzo, the whole application crashed.

Here is the message I got in the Terminal :

File "/opt/pyzo/pyzo-4.1.1/source/pyzo/core/editor.py", line 431, in _onModified
    pyzo.parser.parseThis(self)
  File "/opt/pyzo/pyzo-4.1.1/source/pyzo/core/codeparser.py", line 100, in parseThis
    text = editor.toPlainText()
ValueError: character U+fffffff2 is not in range [U+0000; U+10ffff]
Traceback (most recent call last):
  File "/opt/pyzo/pyzo-4.1.1/source/pyzo/codeeditor/extensions/appearance.py", line 307, in paintEvent
    super(HighlightCurrentLine, self).paintEvent(event)
  File "/opt/pyzo/pyzo-4.1.1/source/pyzo/codeeditor/extensions/appearance.py", line 108, in paintEvent
    super(HighlightMatchingOccurrences, self).paintEvent(event)
  File "/opt/pyzo/pyzo-4.1.1/source/pyzo/codeeditor/extensions/appearance.py", line 216, in paintEvent
    text = cursor.block().text()
ValueError: character U+330080 is not in range [U+0000; U+10ffff]
Traceback (most recent call last):
  File "/opt/pyzo/pyzo-4.1.1/source/pyzo/codeeditor/extensions/appearance.py", line 307, in paintEvent
    super(HighlightCurrentLine, self).paintEvent(event)
  File "/opt/pyzo/pyzo-4.1.1/source/pyzo/codeeditor/extensions/appearance.py", line 108, in paintEvent
    super(HighlightMatchingOccurrences, self).paintEvent(event)
  File "/opt/pyzo/pyzo-4.1.1/source/pyzo/codeeditor/extensions/appearance.py", line 216, in paintEvent
    text = cursor.block().text()
ValueError: character U+3ff00000 is not in range [U+0000; U+10ffff]
^C
[1]+  Erreur de segmentation  pyzo  *(Trad: Segfault pyzo)*

The problem is not serious since I don't think many people will try to name their Python variables "😅".

**Comment by almarklein** [comment]
This seems to be because an inability of the Qt QTextBlock to decode that particular Unicode symbol. A bit surprising. Not sure if there's anything we can do about it. Perhaps Qt5 does better.
