### ISSUE TITLE
Screen freezed

### ISSUE THREAD

**Issue by yltang52** [pyzo/pyzo#487]
I tried the following code in pyzo:

    import turtle

    screen = turtle.Screen()
    screen.setup(500, 500)
    myTurtle = turtle.Turtle()
    myTurtle.forward(150)
    myTurtle.left(90)
    myTurtle.forward(75)
    screen.exitonclick()

I pressed `ctrl-e` to run the code and it runs OK. I then clicked the screen to close the window. But when I pressed `ctrl-e` to run the code again, I got a freezing window with the following error message:

    Traceback (most recent call last):
    File "<tmp 1>", line 5, in <module>
    myTurtle = turtle.Turtle()
    File "/usr/lib/python3.5/turtle.py", line 3816, in __init__
    visible=visible)
    File "/usr/lib/python3.5/turtle.py", line 2557, in __init__
    self._update()
    File "/usr/lib/python3.5/turtle.py", line 2660, in _update
    self._update_data()
    File "/usr/lib/python3.5/turtle.py", line 2646, in _update_data
    self.screen._incrementudc()
    File "/usr/lib/python3.5/turtle.py", line 1292, in _incrementudc
    raise Terminator
    turtle.Terminator

What's the problem?

**Comment by almarklein** [comment]
It looks like turtle is keeping track of when its closed, so running it again confuses it. Better run with CTRL+SHIFT+E :)
