### ISSUE TITLE
Cannot run Pyzo 4.5.1 under Ubuntu 18.04 : zlib version clash

### ISSUE THREAD

**Issue by ysalmon** [pyzo/pyzo#546]
Running pyzo under Ubuntu 18.04 leads to a fatal error with message 
```
Started our command server
Traceback (most recent call last):
  File "/home/almar/miniconda3/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/almar/miniconda3/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "/home/almar/dev/pyzo/pyzo/__main__.py", line 34, in <module>
  File "/home/yann/Téléchargements/pyzo-4.5.1/source/pyzo/__init__.py", line 87, in <module>
    from pyzo.util.qt import QtCore, QtGui, QtWidgets
  File "/home/yann/Téléchargements/pyzo-4.5.1/source/pyzo/util/qt/QtCore.py", line 43, in <module>
    from PySide.QtGui import (QItemSelection, QItemSelectionModel,
ImportError: /home/yann/Téléchargements/pyzo-4.5.1/lib/python3.5/../libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
```

**Comment by almarklein** [comment]
Thanks for the report, and fix. For next release will have to check wether removing zlib.so makes it still work on all Linuxes.
