### ISSUE TITLE
compatibility with Jupyterlab-3

### ISSUE THREAD

**Issue by stonebig** [pyzo/pyzo#717]
trying pyzo with latest jupyterlab-3 (and friends), I get this new strange error:

````
C:\WPy64-3860b1\scripts>pyzo
Traceback (most recent call last):
  File "C:\WPy64-3860b1\python-3.8.6rc1.amd64\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\WPy64-3860b1\python-3.8.6rc1.amd64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\WPy64-3860b1\python-3.8.6rc1.amd64\Scripts\pyzo.exe\__main__.py", line 4, in <module>
  File "C:\WPy64-3860b1\python-3.8.6rc1.amd64\lib\site-packages\pyzo\__init__.py", line 79, in <module>
    from pyzo.core import commandline
  File "C:\WPy64-3860b1\python-3.8.6rc1.amd64\lib\site-packages\pyzo\core\commandline.py", line 175, in <module>
    server = Server(ADDRESS)
  File "C:\WPy64-3860b1\python-3.8.6rc1.amd64\lib\site-packages\pyzo\yoton\clientserver.py", line 97, in __init__
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REis_aliveADDR, 1)
AttributeError: module 'socket' has no attribute 'SO_REis_aliveADDR'

C:\WPy64-3860b1\scripts>
````

**Comment by stonebig** [comment]
it was working before Jupyterlab-3 / Python-3.8.6rc1 / Python-3.9.0rc2, so I'm not exactly sure where is the problem

**Comment by stonebig** [comment]
... it's my faulty version of pyzo, closing
